name: eo-learn-docs
channels:
- conda-forge
dependencies:
- cartopy=0.17.0
- pip:
  - Sphinx==2.4.4
  - sphinx-rtd-theme
  - nbsphinx
  - ipython
  - m2r>=0.2.0

  - ./../core
  - ./../coregistration
  - ./../features
  - ./../geometry
  - ./../io
  - ./../mask
  - ./../ml_tools
  - ./../visualization[FULL]
